### ISSUE TITLE
ConfigurationError: Cursor value does not match its column type

### ISSUE THREAD

**Issue by d30jeff** [Batterii/objection-paginator#4]
Keep getting `ConfigurationError: Cursor value does not match its column type`

```
import { QueryBuilder } from 'objection';
import { Paginator } from 'objection-paginator';
import { News } from './news.model';
export class NewsPaginator extends Paginator<News> {
  static sorts = { default: ['id', 'createdAt'] };

  getBaseQuery(): QueryBuilder<News> {
    return News.query();
  }
}
```

```
async fetchPublishedList(): Promise<any> {
    const paginator = new NewsPaginator({ limit: 10, sort: 'default' });
    const page = await paginator.execute();

    console.log(page);
}
```

**Comment by d30jeff** [comment]
My apologies I missed something in the docs. 
No issues here

**Comment by d30jeff** [comment]
Sorry for the false positive, it turns out that my code was throwing a silent error. The issue mentioned above is still happening.

```
const paginator = await NewsPaginator.getPage({
  limit: 10,
});

return paginator;
```

**Comment by sripberger** [comment]
No worries, I'm happy to help.

What are the types of your "id" and "createdAt" columns in your News model? Not in the database, but after Objection parses them?

This library does run-time type checking in order to fail fast when receiving an invalid cursor. It assumes all cursor values should be strings unless you declare otherwise, so either or both of these values aren't strings, you'll need to set their types as described [here](https://github.com/Batterii/objection-paginator#full-sort-descriptors).

**Comment by d30jeff** [comment]
@sripberger Thank you so much for you clarification. I managed to get it to work now
